name: Calcolo BTP

on:
  schedule:
    - cron: '*/10 * * * *'  # ogni 10 minuti
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install selenium openpyxl PyGithub

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: python calcolo_btp_completo.py
