name: Aggiornamento automatico BTP

on:
  schedule:
    - cron: '*/10 * * * *'  # ogni 10 minuti
  workflow_dispatch:        # permette di avviarlo manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install -r requirements.txt

      - name: Esegui script Python
        run: python calcolo_btp_completo.py
