name: Aggiornamento prezzi titoli di stato

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # ogni ora

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl selenium PyGithub python-dateutil

    - name: Esegui script
      run: python calcolo_btp_completo.py
